services:
  document-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: document-service
    ports:
      - "8080:8080"
    environment:
      - CHROME_PATH=/usr/bin/chromium
    restart: unless-stopped
